### PR TITLE
Revert "Improve CI"

### PR DESCRIPTION
**Pull request by braidsin**
Reverts braidsin/github-actions-for-ci#5

### CODE REVIEW

**Comment by braidsin** [comment]
i can't merge without reviews i reviewed tho

**Review by randomreviewer — COMMENTED** [review]
COOL!!!111

**Review by randomreviewer — APPROVED** [review]
I MEAN COOOL!!1111

**Review by randomreviewer — APPROVED** [review]
APPRoVEE!!1

**Review by randomreviewer — APPROVED** [review]
hOw amNY tIMEas I neeDd to AprotpoVE thiSS?? @braidsin GOOOD! #9 #5 #8

**Pull request merged**
